name: round - Build -> Test
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"
jobs:
  build-and-deploy:
    concurrency: ci-graph-${{ github.head_ref || github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: |
          yarn install
          cd round
          yarn install
          yarn add @graphprotocol/graph-cli

      - name: Prepare subgraph yaml
        run: |
          cd round
          yarn prepare:goerli

      - name: Generate code
        run: |
          cd round
          yarn codegen

      - name: Run tests
        run: |
          cd round
          yarn test

      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
